-- Supabase SQL Editor에서 실행하세요.

-- 1. 사용자 설정 테이블 (API 키 저장용)
CREATE TABLE IF NOT EXISTS public.user_settings (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    openai_api_key_encrypted TEXT,
    openai_api_key_nonce TEXT,
    openai_api_key_tag TEXT,
    youtube_api_key_encrypted TEXT,
    youtube_api_key_nonce TEXT,
    youtube_api_key_tag TEXT,
    replicate_api_key_encrypted TEXT,
    replicate_api_key_nonce TEXT,
    replicate_api_key_tag TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) 설정: 자신의 데이터만 보고 수정 가능
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own settings" 
ON public.user_settings FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own settings" 
ON public.user_settings FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own settings" 
ON public.user_settings FOR UPDATE 
USING (auth.uid() = user_id);

-- 3. API 키 테이블 (개별 저장 방식)
CREATE TABLE IF NOT EXISTS public.api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    encrypted_key TEXT NOT NULL,
    nonce TEXT NOT NULL,
    tag TEXT NOT NULL,
    is_valid BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, provider)
);

-- RLS (Row Level Security) 설정
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own api keys" 
ON public.api_keys FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own api keys" 
ON public.api_keys FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own api keys" 
ON public.api_keys FOR DELETE 
USING (auth.uid() = user_id);

-- 4. 사용자 정보 테이블 (등급 관리용)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE,
    plan TEXT DEFAULT 'free',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS 설정
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" 
ON public.users FOR SELECT 
USING (auth.uid() = id);

-- 내부 관리 또는 유료화 전환 시 사용
CREATE POLICY "Users can update their own profile"
ON public.users FOR UPDATE
USING (auth.uid() = id);

-- ─── 프로젝트 테이블 ───

CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'shorts',
    topic TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft',
    pipeline_config JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own projects"
ON public.projects FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own projects"
ON public.projects FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own projects"
ON public.projects FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own projects"
ON public.projects FOR DELETE
USING (auth.uid() = user_id);

-- ─── 파이프라인 단계 테이블 ───

CREATE TABLE IF NOT EXISTS public.pipeline_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    step TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    provider TEXT,
    provider_config JSONB,
    output_data JSONB,
    error_message TEXT,
    duration_ms INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(project_id, step)
);

ALTER TABLE public.pipeline_steps ENABLE ROW LEVEL SECURITY;

-- pipeline_steps는 프로젝트 소유자만 접근 가능
CREATE POLICY "Users can view their own pipeline steps"
ON public.pipeline_steps FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.projects
        WHERE projects.id = pipeline_steps.project_id
        AND projects.user_id = auth.uid()
    )
);

CREATE POLICY "Users can insert their own pipeline steps"
ON public.pipeline_steps FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.projects
        WHERE projects.id = pipeline_steps.project_id
        AND projects.user_id = auth.uid()
    )
);

CREATE POLICY "Users can update their own pipeline steps"
ON public.pipeline_steps FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM public.projects
        WHERE projects.id = pipeline_steps.project_id
        AND projects.user_id = auth.uid()
    )
);

-- ─── 기존 pipeline_steps 테이블에 컬럼 추가 (이미 테이블이 있는 경우) ───
-- 아래 ALTER 문은 테이블이 이미 존재할 때만 실행하세요.

-- ALTER TABLE public.pipeline_steps ADD COLUMN IF NOT EXISTS output_data JSONB;
-- ALTER TABLE public.pipeline_steps ADD COLUMN IF NOT EXISTS provider VARCHAR(50);
-- ALTER TABLE public.pipeline_steps ADD COLUMN IF NOT EXISTS provider_config JSONB;
