-- Supabase SQL Editor에서 실행하세요.

-- 1. 사용자 설정 테이블 (API 키 저장용)
CREATE TABLE IF NOT EXISTS public.user_settings (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    openai_api_key_encrypted TEXT,
    openai_api_key_nonce TEXT,
    openai_api_key_tag TEXT,
    youtube_api_key_encrypted TEXT,
    youtube_api_key_nonce TEXT,
    youtube_api_key_tag TEXT,
    replicate_api_key_encrypted TEXT,
    replicate_api_key_nonce TEXT,
    replicate_api_key_tag TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) 설정: 자신의 데이터만 보고 수정 가능
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own settings" 
ON public.user_settings FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own settings" 
ON public.user_settings FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own settings" 
ON public.user_settings FOR UPDATE 
USING (auth.uid() = user_id);

-- 2. 프로젝트 테이블 (선택 사항: 이미 SQLAlchemy로 관리 중이라면 필요 없음, 하지만 Supabase DB를 메인으로 쓸 경우 권장)
-- CREATE TABLE IF NOT EXISTS public.projects (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
--     title TEXT NOT NULL,
--     topic TEXT,
--     status TEXT DEFAULT 'pending',
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
-- );
